---

  - name: 1.1.1 Create Separate Partition for /tmp (Scored)
    debug: msg="*** Manually create Separate Partition for /tmp."
    tags:
      - scored
      - section1.1
      - section1.1.1

  - name: 1.1.2 - 1.1.4 Sets nodev,nosuid,noexec option for /tmp Partition (Scored)
    mount: >
      name="/tmp"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev,nosuid,noexec"
    when: item.mount == "/tmp"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.2
      - section1.1.3
      - section1.1.4

  - name: 1.1.5 Create Separate Partition for /var (Scored)
    debug: msg="*** Manually create Separate Partition for /var."
    tags:
      - scored
      - section1.1
      - section1.1.5

  - name: 1.1.6 Bind Mount the /var/tmp directory to /tmp (Scored)
    mount: >
      name="/var/tmp"
      src="/tmp"
      state=mounted
      fstype="none"
      opts="bind"
    when: item.mount == "/tmp"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.6

  - name: 1.1.7 Create Separate Partition for /var/log (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log."
    tags:
      - scored
      - section1.1
      - section1.1.7

  - name: 1.1.8 Create Separate Partition for /var/log/audit (Scored)
    debug: msg="*** Manually create Separate Partition for /var/log/audit."
    tags:
      - scored
      - section1.1
      - section1.1.8

  - name: 1.1.9 Create Separate Partition for /home (Scored)
    debug: msg="*** Manually create Separate Partition for /home."
    tags:
      - scored
      - section1.1
      - section1.1.9

  - name: 1.1.10 Add nodev Option to /home Partition (Scored)
    mount: >
      name="/home"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev"
    when: item.mount == "/home"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.10

  - name: 1.1.11 Add nodev Option to Removable Media Partitions (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - scored
      - section1.1
      - section1.1.11

  - name: 1.1.12 Add noexec Option to Removable Media Partitions (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section1.1
      - section1.1.12

  - name: 1.1.13 Add nosuid Option to Removable Media Partitions (Not Scored)
    debug: msg="*** Not relevant."
    tags:
      - notscored
      - section1.1
      - section1.1.13

  - name: 1.1.14 - 1.1.16 Add noexec Option to /dev/shm Partition (Scored)
    mount: >
      name="/dev/shm"
      src="none"
      state=mounted
      fstype="tmpfs"
      opts="nodev,nosuid,noexec"
    tags:
      - section1.1
      - section1.1.14
      - section1.1.15
      - section1.1.16
      - scored

  - name: 1.1.17 Set sticky bit on all world-writeable directories (Scored)
    debug: msg="*** May be too destructive -- see notes"
    tags:
      - scored
      - section1.1
      - section1.1.17

  - name: 1.2.1 Configure Connection to the RHN RPM repositories (Not Scored)
    command: yum check-update
    register: result
    failed_when: "result.rc == 1"
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.2
      - section1.2.1

  - name: 1.2.2 Verify Red Hat GPG key is installed (Scored)
    command: gpg --quiet --with-fingerprint /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release 
    when: ansible_distribution == "RedHat"
    tags:
      - scored
      - section1.2
      - section1.2.2

  - name: 1.2.3 Verify that gpgcheck is Globally Activated (Scored)
    lineinfile: >
      state=present
      dest=/etc/yum.conf
      regexp=^gpgcheck=
      line=gpgcheck=1
    tags:
      - scored
      - section1.2
      - section1.2.3

  - name: 1.2.5 Obtain software package updates with yum (Not Scored)
    debug: msg="*** Check manually."
    tags:
      - notscored
      - section1.2
      - section1.2.5

  - name: 1.2.6 Verify package integrity using RPM (Not Scored)
    debug: msg="*** Check via cron/AIDE/manually"
    tags:
      - notscored
      - section1.2
      - section1.2.6

