---

  - name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
    file: path=/etc/modprobe.d/CIS.conf state=touch owner=root group=root mode=0600
    changed_when: false
    tags:
      - notscored
      - section1.1
      - section1.1.18
      - section1.1.19
      - section1.1.20
      - section1.1.21
      - section1.1.22
      - section1.1.23
      - section1.1.24

  - name: 1.1.18 Disable Mounting of cramfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install cramfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.18

  - name: 1.1.19 Disable Mounting of freevxfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install freevxfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.19

  - name: 1.1.20 Disable Mounting of jffs2 Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install jffs2 /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.20

  - name: 1.1.21 Disable Mounting of hfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install hfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.21

  - name: 1.1.22 Disable Mounting of hfsplus Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install hfsplus /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.22

  - name: 1.1.23 Disable Mounting of squashfs Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install squashfs /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.23

  - name: 1.1.24 Disable Mounting of udf Filesystems (Not Scored)
    lineinfile: >
      state=present
      dest=/etc/modprobe.d/CIS.conf
      line="install udf /bin/true"
    tags:
      - notscored
      - section1.1
      - section1.1.24

  - name: 1.2.4 Check to see if rhnsd daemon is installed (Not Scored)
    stat: path=/etc/init.d/rhnsd
    register: rhnsd_service
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.2
      - section1.2.4

  - name: 1.2.4 Disable the rhnsd Daemon (Not Scored)
    action: command /sbin/chkconfig rhnsd off
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.2
      - section1.2.4

  - name: 1.3.1 Make sure AIDE is not installed (Scored)
    yum: >
      name=aide
      state=absent
    when: configure_aide
    tags:
      - scoreds
      - section1.3
      - section1.3.1

  - name: 1.3.2 Implement Periodic Execution of File Integrity (Scored)
    cron: >
      name="Run AIDE (CIS 1.3.2)"
      minute="0"
      hour="5"
      job="/usr/sbin/aide --check"
    when: configure_aide
    tags:
      - scored
      - section1.3
      - section1.3.2

  - name: 1.4.1 Enable SELinux in /etc/grub.conf (Scored)
    lineinfile: >
      state=absent
      dest=/etc/grub.conf
      line="selinux=0"
    tags:
      - scored
      - section1.4
      - section1.4.1

  - name: 1.4.1 Enable SELinux in /etc/grub.conf (Scored)
    lineinfile: >
      state=absent
      dest=/etc/grub.conf
      line="enforcing=0"
    tags:
      - scored
      - section1.4
      - section1.4.1

  - name: 1.4.2 Set the SELinux State (Scored)
    yum: >
      name=selinux-policy-targeted
      state=present
    tags:
      - scored
      - section1.4
      - section1.4.2

  - name: 1.4.3 Set the SELinux Policy (Scored)
    selinux: >
      state=enforcing
      policy=targeted
    ignore_errors: yes
    tags:
      - scored
      - section1.4
      - section1.4.3

  - name: 1.4.4 Install SETroubleshoot (Scored)
    yum: >
      name=setroubleshoot
      state=present
    tags:
      - scored
      - section1.4
      - section1.4.4

  - name: 1.4.5 Remove MCS Translation Service (mcstrans) (Scored)
    yum: >
      name=mcstrans
      state=present
    tags:
      - scored
      - section1.4
      - section1.4.5

  - name: 1.4.6 Check for unconfined daemons (Scored)
    debug: msg="*** Check via cron jobs or manually."
    tags:
      - scored
      - section1.4
      - section1.4.6

  - name: 1.5.1 Get Absolute Path to grub.conf
    command: readlink -f /etc/grub.conf
    register: readlink
    changed_when: false
    tags:
      - scored
      - section1.5
      - section1.5.1
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6.8'



  - name: 1.5.1 Set User/Group Owner on /etc/grub.conf (Scored)
    file: >
      path={{ readlink.stdout }}
      owner=root
      group=root
    tags:
      - scored
      - section1.5
      - section1.5.1
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version == '6.8'


  - name: 1.5.1 Get Absolute Path to grub2.cfg
    command: readlink -f /etc/grub2.cfg
    register: readlink
    changed_when: false
    tags:
      - scored
      - section1.5
      - section1.5.1
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version > '7'



  - name: 1.5.1 Set User/Group Owner on /etc/grub2.cfg (Scored)
    file: >
      path={{ readlink.stdout }}
      owner=root
      group=root
    tags:
      - scored
      - section1.5
      - section1.5.1
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version > '7'



  - name: 1.5.2 Get Absolute Path to grub2.conf
    command: readlink -f /etc/grub2.cfg
    register: readlink
    changed_when: false
    tags:
      - scored
      - section1.5
      - section1.5.2
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version > '7'

  - name: 1.5.2 Get Absolute Path to grub.conf
    command: readlink -f /etc/grub.conf
    register: readlink
    changed_when: false
    tags:
      - scored
      - section1.5
      - section1.5.2
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version < 7


  - name: 1.5.2 Sets Permissions on /etc/grub2.cfg (Scored)
    file: path=/boot/grub2/grub.cfg mode=0400
    tags:
      - scored
      - testing 
      - section1.5
      - section1.5.2
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version > '7'

  - name: 1.5.2 Set Permissions on /etc/grub.conf (Scored)
    file: >
      path=/boot/grub/grub.conf mode=0400
    tags:
      - scored
      - section1.5
      - section1.5.2
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version < '7'

  - name: 1.5.3 Set boot loader password (Scored)
    debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
    tags:
      - scored
      - section1.5
      - section1.5.3

  - name: 1.5.4 Require authentication for single-user mode (Scored)
    debug: msg="*** Too destructive for production systems. Evaluate for your environment first."
    tags:
      - scored
      - section1.5
      - section1.5.4

  - name: 1.5.5 Disable Interactive Boot (Scored)
    lineinfile: >
      dest=/etc/sysconfig/init
      regexp=^PROMPT=
      line=PROMPT=no
    tags:
      - scored
      - section1.5
      - section1.5.5
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7'

  - name: 1.6.1 Restrict core dumps (Scored) - via pam
    lineinfile: >
      dest=/etc/security/limits.conf
      line="* hard core 0"
      insertafter=EOF
    tags:
      - scored
      - section1.6
      - section1.6.1
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7'

  - name: 1.6.1 Restrict core dumps (Scored) - via sysctl
    sysctl: >
      name=fs.suid_dumpable
      value=0
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.1
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7'

  - name: 1.6.2 Configure ExecShield (Scored)
    sysctl: >
      name=kernel.exec-shield
      value=1
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.2
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7'

  - name: 1.6.3 Enable Randomized Virtual Memory Region Placement (Scored)
    sysctl: >
      name=kernel.randomize_va_space
      value=2
      state=present
      ignoreerrors=yes
    tags:
      - scored
      - section1.6
      - section1.6.3
    when: ansible_distribution == 'RedHat' and ansible_distribution_major_version >= '7'

  - name: 1.7 Use the Latest OS Release (Not Scored)
    command: >
      cat /etc/redhat-release
    when: ansible_distribution == "RedHat"
    tags:
      - notscored
      - section1.7

