---

  - name: 7.1.1 Set Password Expiration Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_MAX_DAYS\s+"
      line="PASS_MAX_DAYS\t99999"
    tags:
      - scored
      - section7.1
      - section7.1.1

  - name: 7.1.2 Set Password Change Minimum Number of Days (Scored)
    lineinfile: >
      backup=yes 
      state=absent
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_MIN_DAYS\s+"
      line="PASS_MIN_DAYS\t7"
    tags:
      - scored
      - section7.1
      - section7.1.2

  - name: 7.1.3 Set Password Expiring Warning Days (Scored)
    lineinfile: >
      backup=yes 
      state=present 
      dest=/etc/login.defs
      backrefs=yes
      regexp="^PASS_WARN_AGE\s+"
      line="PASS_WARN_AGE\t7"
    tags:
      - scored
      - section7.1
      - section7.1.3

  - name: 7.2 Disable System Accounts (Scored) - preparation
    shell: awk -F':' '($3<500 && $1!="root" && $1!="sync" && $1!="shutdown" && $1!="sync" && $1!="shutdown" && $1!="halt" && $7!="/sbin/nologin") { print $1 }' /etc/passwd
    register: enabled_system_accounts
    changed_when: false
    check_mode: no
    tags:
      - scored
      - section7.2

  
  - name: 7.2 Disable System Accounts (Scored)
    command: /usr/sbin/usermod -s /sbin/nologin {{ item }}
    check_mode: no
    when: enabled_system_accounts.stdout_lines != 'root'
    with_items: "{{ enabled_system_accounts.stdout_lines }}"
    tags:
      - scored
      - section7.2

  - name: 7.3 Set Default Group for root Account (Scored)
    user: >
      name=root
      group=root
    tags:
      - scored
      - section7.3

  - name: 7.4 Set Default umask for Users (Scored)
    lineinfile: 
      state=present
      create=yes
      dest="{{ item }}"
      line="umask 022"
    with_items:
     - /etc/profile.d/cis.sh
    ignore_errors: true
    tags:
      - scored
      - section7.4
    when: ansible_distribution_major_version > 8

  - name: Set Default umask for root (Scored)
    lineinfile:
      state=present
      dest="{{ item }}"
      line="umask 022"
    with_items:
     - /root/.bash_profile
    ignore_errors: true
    tags:
      - scored
      - section7.4
    

  - name: Ensure that /etc/profile.d/cis.sh has correct owner, group and mode
    file: 
      path=/etc/profile.d/cis.sh 
      owner=root
      group=root
      mode=0644
    changed_when: false
    tags:
      - scored
      - section7.4
    when: ansible_distribution_major_version > 8
  
  - name: 7.5 Lock Inactive User Accounts (Scored)
    command: /usr/sbin/useradd -D -f 35
    when: lock_inactive
    tags:
      - scored
      - section7.5

